### PR TITLE
Fix: Remove info.json

### PR DESCRIPTION
**Pull request by aabelmann**
@LvanWissen Bij het overzetten van de info.json naar de info.jsonld, heb je een @base toegevoegd aan de context.
Dit breekt wat paths en query code aan onze kant.
Zover ik kan zien is het niet echt nodig, dus als ik het eruit kan halen, zou ik dat heel fijn vinden.

Zodra het gemerged is, kan ik namelijk ook een "workaround" in onze code eruit halen

### CODE REVIEW

**Comment by LvanWissen** [comment]
Die `@base` zorgt ervoor dat de (relatieve) ids uitgebreid worden naar URIs. Een key `about` wordt daarbij uitgebreid tot `https://diaries.amsterdamtimemachine.nl/about`. 

Zie ook de [json-ld playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fschema.org%2F%22%2C%7B%22%40base%22%3A%22https%3A%2F%2Fdiaries.amsterdamtimemachine.nl%2F%22%7D%5D%2C%22%40graph%22%3A%5B%7B%22%40id%22%3A%22home%22%2C%22%40type%22%3A%22WebPage%22%2C%22name%22%3A%22Amsterdam%22%2C%22description%22%3A%22Hoe%20zag%20het%20dagelijks%20leven%20in%20Amsterdam%20eruit%20in%20de%20Tweede%20Wereldoorlog%3F%20Hoe%20beleefden%20Amsterdammers%20hun%20stad%3F%20De%20Amsterdam%20Diaries%20Time%20Machine%20brengt%20het%20verleden%20tot%20leven%20met%20dagboekfragmenten%20van%20Amsterdamse%20vrouwen%20tijdens%20WOII.%20Navigeer%20door%20hun%20dagboeken.%20Lees%20over%20hun%20familie%20en%20vrienden%2C%20plaatsen%20en%20gebouwen%20in%20de%20stad.%22%7D%2C%7B%22%40id%22%3A%22about%22%2C%22%40type%22%3A%22WebPage%22%2C%22name%22%3A%22About%22%2C%22description%22%3A%22%3Ch2%3EAmsterdam%20Time%20Machine%3C%2Fh2%3E%5Cn%3Cp%3E%3Ca%20href%3D%5C%22https%3A%2F%2Fwww.amsterdamtimemachine.nl%2F%5C%22%20target%3D%5C%22_blank%5C%22%3EDe%20Amsterdam%20Time%20Machine%20(ATM)%3C%2Fa%3E%20is%20een%20open%20onderzoeksinfrastructuur%20over%20de%20geschiedenis%20van%20Amsterdam.%20In%20deze%20%E2%80%98Google%20Earth%20van%20het%20verleden%E2%80%99%20zullen%20gebruikers%20uiteindelijk%20terug%20in%20de%20tijd%20kunnen%20reizen%20en%20door%20de%20stad%20navigeren%20op%20het%20niveau%20van%20buurten%2C%20straten%20en%20huizen.%20Onder%20leiding%20van%20de%20UvA%20wordt%20samengewerkt%20met%20partners%20uit%20het%20veld%20van%20onderzoek%2C%20erfgoed%2C%20de%20creatieve%20industrie%20en%20met%20maatschappelijke%20organisaties.%20Het%20doel%20is%20alle%20digitale%20historische%20data%20van%20de%20stad%20en%20haar%20inwoners%20met%20elkaar%20te%20verbinden%20en%20te%20koppelen%20aan%20historische%20kaarten%20en%203D%20modellen.%20Daarnaast%20wil%20de%20ATM%20bijdragen%20aan%20de%20toekomstige%20inrichting%20van%20de%20stad%20onder%20het%20motto%20%E2%80%98Understanding%20the%20past%20to%20help%20shape%20the%20future%E2%80%99.%3C%2Fp%3E%5Cn%3Ch2%3EAmsterdam%20Diaries%3C%2Fh2%3E%5Cn%3Cp%3EAmsterdam%20Diaries%20is%20een%20samenwerkingsproject%20onder%20leiding%20van%20de%20UvA%20en%20VU%20dat%20persoonlijke%20verhalen%20van%20Amsterdammers%20verzamelt%20en%20bestudeert%20om%20tot%20een%20beter%20begrip%20te%20komen%20van%20het%20leven%20in%20de%20stad%20door%20de%20eeuwen%20heen.%20Doel%20van%20dit%20project%20is%20om%20met%20onderzoek%20naar%20dagboeken%20en%20andere%20egodocumenten%20bij%20te%20dragen%20aan%20de%20lange%20geschiedenis%20van%20Amsterdam%20van%20diversiteit%20door%20de%20verhalen%20van%20stadsbewoners%20met%20een%20verschillende%20culturele%20en%20socio-economische%20achtergrond%20bijeen%20te%20brengen.%3C%2Fp%3E%5Cn%3Cp%3EVoor%20de%20nieuwe%20applicatie%20is%20een%20selectie%20gemaakt%20van%20een%20aantal%20dagboeken%20uit%20het%20Amsterdam%20Diaries-project.%20De%20dagboeken%20komen%20uit%20de%20collecties%20van%20het%20Stadsarchief%2C%20Atria%2C%20het%20Joods%20Museum%20en%20het%20Verzetsmuseum.%20Het%20betreft%20dagboeken%20die%20alle%20gaan%20over%20de%20periode%20van%20de%20Tweede%20Wereldoorlog.%20Door%20het%20combineren%20van%20de%20dagboekfragmenten%20van%20deze%20bijzondere%20vrouwen%20ontstaat%20een%20persoonlijke%20blik%20op%20een%20roerige%20periode%20in%20de%20Amsterdamse%20geschiedenis.%3C%2Fp%3E%5Cn%3Cp%3EWe%20zijn%20ge%C3%AFnteresseerd%20in%20aanvullend%20materiaal%20en%20andere%20verhalen%20van%20vrouwen%20in%20Amsterdam%20tijdens%20de%20Tweede%20Wereldoorlog.%20Contact%20opnemen%20kan%20via%20het%20e-mailadres%20%3Ca%20href%3D%5C%22mailto%3Am.j.m.rensen%40uva.nl%5C%22%3Em.j.m.rensen%40uva.nl%3C%2Fa%3E.%3C%2Fp%3E%5Cn%3Cp%3EDe%20applicatie%20is%20ontwikkeld%20door%20%3Ca%20href%3D%5C%22https%3A%2F%2Fwww.totaldesign.com%2F%5C%22%20target%3D%5C%22_blank%5C%22%3ETotal%20Design%3C%2Fa%3E%2C%20met%20steun%20van%20het%20%3Ca%20href%3D%5C%22https%3A%2F%2Fnetwerkdigitaalerfgoed.nl%2F%5C%22%20target%3D%5C%22_blank%5C%22%3ENetwerk%20Digitaal%20Erfgoed.%3C%2Fa%3E%3C%2Fp%3E%22%7D%2C%7B%22%40id%22%3A%22organisaties%22%2C%22%40type%22%3A%22WebPage%22%2C%22name%22%3A%22Alle%20organisaties%22%2C%22description%22%3A%22Ontdek%20de%20diverse%20perspectieven%20over%20specifieke%20organisaties%20die%20terugkomen%20in%20diverse%20dagboeken.%22%7D%2C%7B%22%40id%22%3A%22personen%22%2C%22%40type%22%3A%22WebPage%22%2C%22name%22%3A%22Alle%20personen%22%2C%22description%22%3A%22Ontdek%20personen%20die%20worden%20genoemd%20in%20diverse%20dagboeken.%22%7D%2C%7B%22%40id%22%3A%22themas%22%2C%22%40type%22%3A%22WebPage%22%2C%22name%22%3A%22Alle%20thema's%22%2C%22description%22%3A%22Thema's%20worden%20be%C3%AFnvloed%20door%20diverse%20perspectieven%20en%20grote%20gebeurtenissen.%20Schrijvers%2C%20als%20weerspiegeling%20van%20hun%20tijd%2C%20verwerken%20deze%20invloeden%20in%20hun%20werk%2C%20waardoor%20unieke%20en%20veelzijdige%20verhalen%20ontstaan.%22%7D%2C%7B%22%40id%22%3A%22dagboekschrijfsters%22%2C%22%40type%22%3A%22WebPage%22%2C%22name%22%3A%22Alle%20dagboekschrijfsters%22%2C%22description%22%3A%22Ontdek%20de%20diverse%20perspectieven%20die%20dagboeken%20ons%20bieden%20en%20laat%20je%20inspireren%20door%20de%20persoonlijke%20verhalen%20van%20anderen.%22%7D%2C%7B%22%40id%22%3A%22amsterdam%22%2C%22%40type%22%3A%22WebPage%22%2C%22name%22%3A%22Wat%20beleefden%20de%20dagboekschrijfsters%20in%20Amsterdam%3F%22%2C%22description%22%3A%22In%20de%20dagboeken%20was%20veel%20aandacht%20voor%20de%20beslommeringen%20van%20alle%20dag.%20Onvermijdelijk%20drong%20ook%20de%20oorlog%20daarin%20door.%20Bekijk%20op%20deze%20kaart%20waar%20in%20Amsterdam%20het%20dagelijks%20leven%20van%20de%20dagboekschrijfsters%20zich%20afspeelde%20en%20wat%20ze%20erover%20in%20hun%20dagboeken%20noteerden.%22%7D%5D%7D). 

Als het geen valide URIs zijn, dan is het hebben van dit bestand in JSON-LD ook niet zo nuttig.

**Comment by aabelmann** [comment]
@LvanWissen Ik begrijp je punt maar binnen de applicatie worden er geen URI's gebruikt, we gebruiken een relatief path als ID. We kunnen dit wel omzetten naar URI's maar dan moeten we aan de Nuxt kant ook de `@base` weten en dit appenden met het relatieve path.

**Comment by LvanWissen** [comment]
Is het een optie om die `@base` te negeren bij het inlezen? Of desnoods de hele `@context`?

**Comment by aabelmann** [comment]
> Is het een optie om die `@base` te negeren bij het inlezen? Of desnoods de hele `@context`?

Dat is hetgene wat ik nu als workaround heb

**Comment by aabelmann** [comment]
Ik laat de info.jsonld zoals het is maar haal wel de info.json wel, zodat het niet verwarrend is.

**Pull request merged**
